import test from 'node:test';
import assert from 'node:assert/strict';
import { buildSeedState } from '../../src/data/seed';
import { applyCommand, type Command } from '../../src/data/commands';
import { myTransfers, openRequests } from '../../src/data/selectors';
import { comprobarPermiso } from '../src/permisos';
import type { AppState } from '../../src/data/types';
let n = 0;
const at = '2026-09-14T12:00:00.000Z';
function cmd(x: object, userId = 'u-juan'): Command { return { id: `jon-${++n}`, at, userId, ...x } as Command; }
function base() { const s = buildSeedState(); s.requests = []; s.preparations = []; s.vehicles = [{ ...s.vehicles[0], id: 'coche', status: 'aparcado', salesRep: 'Juan', location: { siteId: 'leioa' }, locationObservedAt: '2026-01-01T00:00:00Z' }]; return s; }
function pedir(s = base(), tipo = 'traslado', extra = {}) { return applyCommand(s, cmd({ type: 'request.create', requestType: tipo, vehicleId: 'coche', siteId: 'galdakao', to: { siteId: 'galdakao' }, carrierId: 'gruas-francis', ...extra })); }
function mover(s: AppState, siteId: string) { return applyCommand(s, cmd({ type: 'movement.register', vehicleId: 'coche', to: { siteId }, completesTransfer: true }, 'u-log')); }
function cancelar(s: AppState, user = 'u-juan') { return applyCommand(s, cmd({ type: 'request.cancel', requestId: s.requests[0].id, reason: 'El cliente cambia la entrega' }, user)); }
function permiso(s: AppState, user: string) { return comprobarPermiso(s, s.users.find(u => u.id === user)!, cmd({ type: 'request.cancel', requestId: s.requests[0].id, reason: 'Cambio' }, user)); }

test('1 traslado llega al destino correcto', () => assert.equal(mover(pedir(), 'galdakao').requests[0].status, 'terminada'));
test('2 otro destino no completa el traslado', () => assert.equal(mover(pedir(), 'sondika').requests[0].status, 'solicitada'));
test('3 movimiento interno no completa el traslado', () => assert.equal(mover(pedir(), 'leioa').requests[0].status, 'solicitada'));
test('4 no cierra otro traslado abierto heredado', () => { const s = pedir(); s.requests.unshift({ ...s.requests[0], id: 'otro', to: { siteId: 'irun' }, siteId: 'irun' }); const t = mover(s, 'galdakao'); assert.equal(t.requests[0].status, 'solicitada'); assert.equal(t.requests[1].status, 'terminada'); });
test('5 empresa asignada recibe el traslado', () => { const s = pedir(); assert.equal(s.requests[0].carrierId, 'gruas-francis'); assert.equal(myTransfers(s, 'u-iker').length, 1); assert.equal(myTransfers(s, 'u-aitor').length, 0); });
test('6 sin empresa no aparece a transportistas', () => { const s = pedir(base(), 'traslado', { carrierId: null }); s.requests[0].assignedTo = 'u-iker'; assert.equal(myTransfers(s, 'u-iker').length, 0); assert.equal(openRequests(s).length, 1); });
test('7 no duplica traslados incompatibles', () => { const s = pedir(); assert.equal(pedir(s, 'traslado', { siteId: 'irun', to: { siteId: 'irun' } }).requests.length, 1); });
test('8 no duplica solicitudes equivalentes y respeta repaso', () => { const s = pedir(base(), 'preparacion'); assert.equal(pedir(s, 'preparacion').requests.length, 1); assert.equal(pedir(s, 'preparacion', { prepTipo: 'repaso' }).requests.length, 2); });
test('9 no duplica preparación ya abierta', () => { let s = base(); s = applyCommand(s, cmd({ type: 'prep.create', vehicleId: 'coche', siteId: 'galdakao' }, 'u-log')); s = applyCommand(s, cmd({ type: 'prep.create', vehicleId: 'coche', siteId: 'galdakao' }, 'u-log')); assert.equal(s.preparations.length, 1); assert.equal(pedir(s, 'preparacion').requests.length, 0); });
test('10 creador cancela traslado pendiente', () => { const s = pedir(); assert.equal(permiso(s, 'u-juan'), null); assert.equal(cancelar(s).requests[0].status, 'cancelada'); });
test('11 creador no cancela traslado iniciado', () => { const s = pedir(); s.requests[0].pickedUpAt = at; assert.notEqual(permiso(s, 'u-juan'), null); assert.equal(cancelar(s).requests[0].status, 'solicitada'); });
test('12 logística cancela iniciado sin moverlo', () => { const s = pedir(); s.requests[0].status = 'en_ruta'; s.requests[0].pickedUpAt = at; assert.equal(permiso(s, 'u-log'), null); const t = cancelar(s, 'u-log'); assert.equal(t.requests[0].status, 'cancelada'); assert.deepEqual(t.vehicles[0].location, s.vehicles[0].location); });
test('13 cancela preparación pendiente', () => assert.equal(cancelar(pedir(base(), 'preparacion')).requests[0].status, 'cancelada'));
test('14 comercial no cancela preparación iniciada', () => { let s = pedir(base(), 'preparacion'); s = applyCommand(s, cmd({ type: 'prep.create', vehicleId: 'coche', siteId: 'galdakao' }, 'u-log')); s = applyCommand(s, cmd({ type: 'prep.start', prepId: s.preparations[0].id }, 'u-pedro')); assert.notEqual(permiso(s, 'u-juan'), null); });
test('15 cancelación conserva autor motivo fecha y trazabilidad, es idempotente', () => { const s = pedir(); const c = cmd({ type: 'request.cancel', requestId: s.requests[0].id, reason: 'Cambio de cliente' }); const t = applyCommand(s, c); assert.equal((t.requests[0] as any).cancelledBy, 'u-juan'); assert.equal((t.requests[0] as any).cancelledAt, at); assert.equal((t.requests[0] as any).cancelReason, 'Cambio de cliente'); assert.ok(t.events.some(e => e.title === 'Solicitud cancelada')); assert.deepEqual(applyCommand(t, c), t); });
test('16 cancelada sale de colas sin cambiar ubicación', () => { const s = pedir(); const t = cancelar(s); assert.equal(openRequests(t).length, 0); assert.equal(myTransfers(t, 'u-iker').length, 0); assert.deepEqual(t.vehicles[0].location, s.vehicles[0].location); });
test('17 transportista no cancela ni siquiera con permisos ampliados', () => { const s = pedir(); s.config.roles.find(r => r.id === 'transportista')!.permissions.push('solicitudes.gestionar'); assert.notEqual(permiso(s, 'u-iker'), null); });
test('18 movimiento a zona sin plazas', () => { let s = base(); s = applyCommand(s, cmd({ type: 'zone.upsert', zone: { id: 'exterior', siteId: 'leioa', name: 'Parking exterior', kind: 'parking', capacity: 0 } }, 'u-admin')); s = applyCommand(s, cmd({ type: 'movement.register', vehicleId: 'coche', to: { siteId: 'leioa', zoneId: 'exterior' } }, 'u-log')); assert.deepEqual(s.vehicles[0].location, { siteId: 'leioa', zoneId: 'exterior' }); assert.equal(s.positions.filter(p => p.zoneId === 'exterior').length, 0); });
test('19 recepción sin posición sitúa en la zona', () => { let s = base(); s.zones.push({ id: 'exterior', siteId: 'leioa', name: 'Exterior', kind: 'parking', capacity: 0 }); const c = cmd({ type: 'reception.create', truckPlate: 'TEST', carrier: 'Test', siteId: 'leioa' }, 'u-log'); s = applyCommand(s, c); s = applyCommand(s, cmd({ type: 'reception.line', receptionId: `rec-${c.id}`, ref: s.vehicles[0].vin8, unloaded: true, zoneId: 'exterior', positionId: null }, 'u-log')); assert.equal(s.vehicles[0].location?.zoneId, 'exterior'); assert.ok(!s.vehicles[0].location?.positionId); });
test('20 llaves opcionales e independientes y con trazabilidad', () => { let s = base(); for (const x of [{ primary: 'Recepción' }, { secondary: 'Cliente' }, { primary: '' }, { secondary: '' }]) { s = applyCommand(s, cmd({ type: 'vehicle.setKeys', vehicleId: 'coche', ...x }, 'u-log')); } assert.equal((s.vehicles[0] as any).primaryKeyLocation, null); assert.equal((s.vehicles[0] as any).secondaryKeyLocation, null); assert.equal(s.events.filter(e => e.title === 'Ubicación de llaves actualizada').length, 4); });
test('21 movimientos, cancelación y entrega no alteran llaves', () => { let s = base(); s = applyCommand(s, cmd({ type: 'vehicle.setKeys', vehicleId: 'coche', secondary: 'Caja fuerte' }, 'u-log')); for (const t of [cancelar(pedir(s)), mover(pedir(s), 'galdakao')]) { assert.equal((t.vehicles[0] as any).secondaryKeyLocation, 'Caja fuerte'); assert.ok(!(t.vehicles[0] as any).primaryKeyLocation); } });

test('22 recuento en parking sin posiciones registra la zona observada', () => { let s = base(); s.zones.push({ id: 'exterior', siteId: 'galdakao', name: 'Exterior', kind: 'parking', capacity: 0 }); const c = cmd({ type: 'count.create', siteId: 'galdakao', zoneId: 'exterior', code: 'TEST' }, 'u-log'); s = applyCommand(s, c); s = applyCommand(s, cmd({ type: 'count.finding', countId: s.counts[0].id, vehicleId: 'coche' }, 'u-log')); assert.deepEqual(s.vehicles[0].location, { siteId: 'galdakao', zoneId: 'exterior' }); assert.equal(s.counts[0].found.length, 1); });
test('23 backend permite al comercial solicitar hacia Galdakao y deniega manipular cancelada', () => { const s = pedir(); const u = s.users.find(u => u.id === 'u-juan')!; assert.equal(comprobarPermiso(s, u, cmd({ type: 'request.create', requestType: 'traslado', vehicleId: 'coche', siteId: 'galdakao', to: { siteId: 'galdakao' }, carrierId: 'gruas-francis' })), null); const t = cancelar(s); assert.notEqual(comprobarPermiso(t, t.users.find(u=>u.id==='u-log')!, cmd({type:'request.update',requestId:t.requests[0].id,status:'solicitada'},'u-log')), null); });
test('24 logística cancela preparación iniciada y detiene sus relojes sin completar checklist', () => { let s = pedir(base(), 'preparacion'); s = applyCommand(s, cmd({ type: 'prep.create', vehicleId: 'coche', siteId: 'galdakao', preparerId:'u-jon' }, 'u-log')); s = applyCommand(s, cmd({ type: 'prep.start', prepId: s.preparations[0].id }, 'u-jon')); const t = cancelar(s, 'u-log'); assert.equal(t.preparations[0].runState, 'cancelado'); assert.equal(t.preparations[0].runningSince, null); assert.deepEqual(t.preparations[0].items,s.preparations[0].items); assert.ok(t.inbox.some(n=>n.title==='Solicitud cancelada'&&n.userIds?.includes('u-jon'))); const retrasado = applyCommand(t,cmd({type:'prep.start',prepId:t.preparations[0].id},'u-jon')); assert.deepEqual(retrasado,t); });
test('25 segunda llave se conserva al cambiar solo principal', () => { let s = applyCommand(base(), cmd({type:'vehicle.setKeys',vehicleId:'coche',secondary:'Cliente'},'u-log')); s = applyCommand(s,cmd({type:'vehicle.setKeys',vehicleId:'coche',primary:'Taller'},'u-log')); assert.equal(s.vehicles[0].secondaryKeyLocation,'Cliente'); assert.equal(s.vehicles[0].primaryKeyLocation,'Taller'); s=applyCommand(s,cmd({type:'vehicle.setKeys',vehicleId:'coche',primary:null},'u-log')); assert.equal(s.vehicles[0].secondaryKeyLocation,'Cliente'); assert.equal(s.vehicles[0].primaryKeyLocation,null); });

test('26 reintentos antiguos no reabren una solicitud cancelada', () => { const s = cancelar(pedir()); assert.deepEqual(applyCommand(s,cmd({type:'request.update',requestId:s.requests[0].id,status:'en_ruta'},'u-iker')),s); });
